#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml' 'dnspython' 'requests')

function check_and_install() {
    if ! dpkg -s $1 2>&1 > /dev/null; then
        apt-get -y install $1
    fi
}

PYTHON="python3"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON}-${dep}
done
check_and_install patch

exec ./hooks/install.real
