version: '2'
services:
  node-init:
    image: "{{ container_registry }}/contrail-node-init:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_kubemanager.env
    environment:
      - CONTRAIL_STATUS_IMAGE="{{ container_registry }}/contrail-status:{{ contrail_version_tag }}"
    privileged: true
    pid: host
    network_mode: "host"
    volumes:
      - /usr/bin:/host/usr/bin
      - /etc/contrail/ssl/{{ module }}:/etc/contrail/ssl
      - /etc/sysctl.d:/etc/sysctl.d
      - /etc/hosts:/etc/hosts
      - /var/log/contrail:/var/log/contrail
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/crashes:/var/crashes
{{ logging | indent(4,True) }}
  kubemanager:
    image: "{{ container_registry }}/contrail-kubernetes-kube-manager:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_kubemanager.env
    network_mode: host
    environment:
      - K8S_TOKEN={{ kube_manager_token }}
    volumes_from:
      - node-init
    depends_on:
      - node-init
    restart: always
{{ logging | indent(4,True) }}
