#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

# run update - it's required if it's installed in lxd container
apt-get update

declare -a DEPS=('python' 'python-yaml' 'python-pip')

check_and_install() {
    pkg="${1}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

for dep in ${DEPS[@]}; do
    check_and_install ${dep}
done
